version: '3.7'

services:
  namenode:
    image: apache/hadoop:3.3.1
    container_name: namenode
    ports:
      - "9870:9870"
    volumes:
      - namenode-data:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=hadoop-cluster

  datanode:
    image: apache/hadoop:3.3.1
    container_name: datanode
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - HDFS_CONF_dfs_namenode_name_dir=file:///hadoop/dfs/name
      - HDFS_CONF_dfs_datanode_data_dir=file:///hadoop/dfs/data
    volumes:
      - datanode-data:/hadoop/dfs/data
    depends_on:
      - namenode

  spark-master:
    image: apache/spark:3.2.1
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_NO_DAEMONIZE=true

  spark-worker-1:
    image: apache/spark:3.2.1
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512m

volumes:
  namenode-data:
  datanode-data:
